### ISSUE TITLE
Buffer Tool - Owner Field Blank

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#42]
### Steps to reproduce
1. Load the map at http://test.mapserv.utah.gov/daq/
2. Click the Buffer Radius Tool at the bottom of the application screen.
3. The Buffer Radius tool appears in the tool container.
4. Enter a radius value and click activate.
5. Click on a POI interest using the cursor buffer icon.
6. See results returned in the tool container.
7. Two fields for each result is returned, AI Number and Owner. However, Owner is always empty.
8. I don't think there is an owner attribute for the facilities layer, but there is an "Operator Name" attribute.  I think this should be used rather than "owner".

### Expected behavior
Replace the owner field in the buffer tool results table with an operator name field. When results are returned, even in instances where the AI # is "0", you will still have an operator name returned.

**Comment by steveoh** [comment]
@woswald are these modifications specific to certain layers or is this modification for all layers?

**Comment by woswald** [comment]
@steveoh 
I believe the Buffer tool only works with the 2014 O&G Facilities layer, so it should be specific to that layer.

**Comment by woswald** [comment]
@steveoh Should the buffer tool be working the in the current 1.8.0 release?

**Comment by steveoh** [comment]
I just verified that it is working in the 1.8.0 release.

**Comment by woswald** [comment]
The Buffer tool is not currently working for me in the 1.8.0 release.  I haven't been able to verify if the owner field is working yet because of this.

Steps to Reproduce
1) After Loading https://test.mapserv.utah.gov/daq
2) Click on the Buffer tool icon.
3) In the Tool Window, enter 7500 meters. Click Activate.
4) No buffer appears on the map.
5) If I click on the map near some Facilities points, the headers for the results table will appear (AI Number, Operator Name) but no data is returned. (see image) 
![image](https://cloud.githubusercontent.com/assets/7386943/26411935/798865f6-4064-11e7-9555-75b906c79ddc.png)

Browser:
Chrome

**Comment by steveoh** [comment]
Will you copy paste your dev tools console. I don't understand why this works for me and not you.

**Comment by woswald** [comment]
Let me know if there is a better way to copy paste this:

```
app/App::constructor Arguments(2)
dojo.js:6 app/App::postCreate Arguments(0)
dojo.js:101 app.Toaster::postCreate Arguments(0)
dojo.js:101 app.Toaster::setupConnections Arguments(0)
dojo.js:6 app/App::initMap Arguments(0)
dojo.js:20 app.GraphicsController::initialize Arguments(2)
dojo.js:6 app/App::startup Arguments(0)
content/dojo/resources/blank.gif Failed to load resource: the server responded with a status of 404 (Not Found)
contentScript.js:77 inserted the extension element
contentScript.js:43 dispatching the event: emc.ctf.addonInited
dojo.js:1 Error: Token Required
    at Object.a.load (dojo.js:17)
    at dojo.js:1
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at dojo.js:1
    at i (dojo.js:2)
t @ dojo.js:1
dojo.js:1 Error: Token Required
    at Object.a.load (dojo.js:17)
    at dojo.js:1
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at dojo.js:1
    at i (dojo.js:2)
t @ dojo.js:1
dojo.js:1 Error: Token Required
    at Object.a.load (dojo.js:17)
    at dojo.js:1
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at dojo.js:1
    at i (dojo.js:2)
t @ dojo.js:1
dojo.js:1 Error: Token Required
    at Object.a.load (dojo.js:17)
    at dojo.js:1
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at k (dojo.js:2)
    at g (dojo.js:2)
    at a.Deferred.resolve.callback (dojo.js:2)
    at dojo.js:1
    at i (dojo.js:2)
t @ dojo.js:1
dojo.js:6 app/App::setupConnections Arguments(0)
dojo.js:6 app/App::_applyAliasProperty Arguments(1)
dojo.js:20 app.MapController::initialize Arguments(1)
discover.agrc.utah.gov/login/path/sector-snake-paradox-reply/wmts?SERVICE=W…AT=image/png&TILEMATRIXSET=0to19&TILEMATRIX=0to19:07&TILEROW=50&TILECOL=28 Failed to load resource: the server responded with a status of 400 ()
discover.agrc.utah.gov/login/path/sector-snake-paradox-reply/wmts?SERVICE=W…AT=image/png&TILEMATRIXSET=0to19&TILEMATRIX=0to19:07&TILEROW=48&TILECOL=28 Failed to load resource: the server responded with a status of 400 ()
discover.agrc.utah.gov/login/path/sector-snake-paradox-reply/wmts?SERVICE=W…AT=image/png&TILEMATRIXSET=0to19&TILEMATRIX=0to19:07&TILEROW=46&TILECOL=28 Failed to load resource: the server responded with a status of 400 ()
discover.agrc.utah.gov/login/path/sector-snake-paradox-reply/wmts?SERVICE=W…AT=image/png&TILEMATRIXSET=0to19&TILEMATRIX=0to19:07&TILEROW=47&TILECOL=28 Failed to load resource: the server responded with a status of 400 ()
discover.agrc.utah.gov/login/path/sector-snake-paradox-reply/wmts?SERVICE=W…AT=image/png&TILEMATRIXSET=0to19&TILEMATRIX=0to19:07&TILEROW=49&TILECOL=28 Failed to load resource: the server responded with a status of 400 ()
dojo.js:1 f
t @ dojo.js:1
dojo.js:1 f
t @ dojo.js:1
dojo.js:1 f
t @ dojo.js:1
dojo.js:1 f
t @ dojo.js:1
dojo.js:1 f
t @ dojo.js:1
dojo.js:6 app/App:activateTool Arguments(1)
dojo.js:20 app.Buffer::postCreate Arguments(0)
dojo.js:20 app.Buffer::activate Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
content/esri/geometry/geometryenginewebworker.js Failed to load resource: the server responded with a status of 404 (Not Found)
dojo.js:40 Worker Error: undefined
In undefined on undefined
dojo.js:20 app.Buffer:_buffer Arguments(1)
content/esri/geometry/geometryenginewebworker.js Failed to load resource: the server responded with a status of 404 (Not Found)
dojo.js:40 Worker Error: undefined
In undefined on undefined
dojo.js:20 app.Buffer:_buffer Arguments(1)
content/esri/geometry/geometryenginewebworker.js Failed to load resource: the server responded with a status of 404 (Not Found)
dojo.js:40 Worker Error: undefined
In undefined on undefined
dojo.js:20 app.Buffer:_buffer Arguments(1)
content/esri/geometry/geometryenginewebworker.js Failed to load resource: the server responded with a status of 404 (Not Found)
dojo.js:40 Worker Error: undefined
In undefined on undefined
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_intersect Arguments(1)
dojo.js:20 app.Buffer:_initGrid Arguments(0)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
dojo.js:20 app.Buffer:_buffer Arguments(1)
```

**Comment by steveoh** [comment]
You need the / at the end of the url while we are in test still.

**Comment by woswald** [comment]
Sorry! My bad. It think I just clicked the email link, and forgot to check for that.

**Comment by woswald** [comment]
This appears to be working perfectly now.
